### ISSUE TITLE
Tests 0-5 of FlexLinkCoder.py output error message

### ISSUE THREAD

**Issue by MustBeArt** [OpenResearchInstitute/Neptune#3]
Changing the test number from 6 to any value 0 to 5 gives the error shown below. I think this is just falling through to the graphing code that's part of test 6. Probably just need to add an indentation level to all the matplotlib code at the end of the file.

```
python % python3 FlexLinkCoder.py
Test 5 has passed.
Traceback (most recent call last):
  File "/Users/kb5mu/Documents/git/neptune/FlexLink/models/transmitter/python/FlexLinkCoder.py", line 837, in <module>
    plt.semilogy(SnrdB_List, BER_List[0], 'r')
                 ^^^^^^^^^^
NameError: name 'SnrdB_List' is not defined
```

**Comment by Abraxas3d** [comment]
No longer an active target for development, so keeping an open issue is moot.
