### ISSUE TITLE
typographical errors in FlexLink specification document

### ISSUE THREAD

**Issue by Abraxas3d** [OpenResearchInstitute/Neptune#4]
Page 9, Figure 2-2, "k=499" is probably "k=449"
Page 11, "visa-versa" is probably "vice versa"
Page 20, "bugger" is probably "buffer"

**Comment by MustBeArt** [comment]
k=499 is probably k=449, not 459.

Style guides say that "vice versa" does not contain a hyphen.

**Comment by Abraxas3d** [comment]
Thank you - updated issue.

**Comment by Abraxas3d** [comment]
20.48 MHz as a master clock doesn't work with respect to the rate at which samples are sent out over the antenna. 1024 vs 1106 is not an integer related set of numbers. Discussions of master clock rates should probably not be in the specification, since the ADC/DAC/processor clock rates will probably not be related to the communications sample rates.

This affects things like Preamble lengths, where the time specified conflicts with the number of samples specified, if we use the transmit sample rate instead of the baseband sample rate. We've interpreted the time specified as having priority over the number of samples.

**Comment by Abraxas3d** [comment]
Unless pilot tones have a time-out, we need a postamble to indicate end of transmission. Otherwise, it's not possible to know when the link was lost vs. when the link was ended.

**Comment by Abraxas3d** [comment]
For the AGC Burst, it says both 4 and 5 microseconds in the places where this preamble is discussed.

**Comment by Abraxas3d** [comment]
"unmapped" and "punctured" are two different things. It looks like, from looking at the Python model, that the samples at tone 0 are punctured, or overwritten, and the position is not left unmapped, which would be "avoided". It would be an improvement to make it clear that this is puncturing and not leaving it unmapped. It is mapped - it's just overwritten with a zero value since it (and possibly some other tones nearby) will not survive modulation.

**Comment by Abraxas3d** [comment]
No longer an active target for development, so keeping an open issue is moot.
